name: Docker Image Build
on:
  push

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./22-jdk21-mvn/Dockerfile
            tag: somik123/ubuntu:22-jdk21-mvn
          - dockerfile: ./22-jdk21/Dockerfile
            tag: somik123/ubuntu:22-jdk21

    steps:
      # Step 1 ==> Checkout code
      - 
        name: Checkout the code from github repo
        uses: actions/checkout@v4

      # Step 2 ==> Docker login
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Step 3 ==> Docker build and push
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.tag }}
